name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install 3.13

      - name: Install dependencies
        run: |
          uv sync
          uv add ruff

      - name: Run ruff format check
        run: uv run ruff format --check .

      - name: Run ruff linter
        run: uv run ruff check .

      - name: Run tests
        run: uv run pytest tests/ -v
